name: lighthouse
description: "Lighthouse is a beacon of hope, empowering a Christian denomination's disaster relief efforts by seamlessly coordinating volunteers, donations, and projects to rebuild communities after natural disasters."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  latlong2: 0.9.1
  flutter_map: ^8.0.0
  image_picker_for_web: ^3.0.0
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  supabase_flutter: ^2.5.0
  http: ^1.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
